// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSkx7HtbPyp8yuK8uycA9WO1svzjsW65s',
    appId: '1:219343461160:web:03a6531e4aecb151bbce1d',
    messagingSenderId: '219343461160',
    projectId: 'salon-app-7b3f5',
    authDomain: 'salon-app-7b3f5.firebaseapp.com',
    databaseURL: 'https://salon-app-7b3f5-default-rtdb.firebaseio.com',
    storageBucket: 'salon-app-7b3f5.firebasestorage.app',
    measurementId: 'G-CRHQ39JZ2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ4DLi2incGP3c246uUNqvw8wbFpSPgv8',
    appId: '1:219343461160:android:6d9708413b93d5fbbbce1d',
    messagingSenderId: '219343461160',
    projectId: 'salon-app-7b3f5',
    databaseURL: 'https://salon-app-7b3f5-default-rtdb.firebaseio.com',
    storageBucket: 'salon-app-7b3f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ADLiJbw7ueXA8Pae16mqZngFHBrJbeM',
    appId: '1:219343461160:ios:b48577cb69b1de06bbce1d',
    messagingSenderId: '219343461160',
    projectId: 'salon-app-7b3f5',
    databaseURL: 'https://salon-app-7b3f5-default-rtdb.firebaseio.com',
    storageBucket: 'salon-app-7b3f5.firebasestorage.app',
    iosClientId:
        '219343461160-dr0lcrpjf932j2aq09ph4u8qoa8u1ie5.apps.googleusercontent.com',
    iosBundleId: 'com.example.salon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ADLiJbw7ueXA8Pae16mqZngFHBrJbeM',
    appId: '1:219343461160:ios:b48577cb69b1de06bbce1d',
    messagingSenderId: '219343461160',
    projectId: 'salon-app-7b3f5',
    databaseURL: 'https://salon-app-7b3f5-default-rtdb.firebaseio.com',
    storageBucket: 'salon-app-7b3f5.firebasestorage.app',
    iosClientId:
        '219343461160-dr0lcrpjf932j2aq09ph4u8qoa8u1ie5.apps.googleusercontent.com',
    iosBundleId: 'com.example.salon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSkx7HtbPyp8yuK8uycA9WO1svzjsW65s',
    appId: '1:219343461160:web:42f44cb576691f83bbce1d',
    messagingSenderId: '219343461160',
    projectId: 'salon-app-7b3f5',
    authDomain: 'salon-app-7b3f5.firebaseapp.com',
    databaseURL: 'https://salon-app-7b3f5-default-rtdb.firebaseio.com',
    storageBucket: 'salon-app-7b3f5.firebasestorage.app',
    measurementId: 'G-77BKW8G5WY',
  );
}
