gradle.beforeProject { proj ->
    proj.plugins.withId("com.android.library") {
        proj.android.lint {
            disable "NullSafeMutableLiveData"
        }
    }
    proj.plugins.withId("com.android.application") {
        proj.android.lint {
            disable "NullSafeMutableLiveData"
        }
    }
}
